# Copyright (C) 2023, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook call all necessary playbooks to deploy the tests and test
# SEAPATH.

---
- name: Detect Seapath distribution
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  roles:
    - detect_seapath_distro
- name: Import test_deploy_cukinia_tests playbook
  import_playbook: ./test_deploy_cukinia_tests.yaml
  when: seapath_distro == "Debian"

- name: Import test_run_cukinia playbook
  import_playbook: ./test_run_cukinia.yaml
